/*  
 *   File: ShortStackDev.c
 *   Generated by LonTalk Interface Developer 4.00.11
 *
 *   Created on Thu Nov 13 09:55:48 2014
 *   This file applies to the device with program ID 90:00:33:06:00:02:04:02
 *
 *   Copyright (c) Echelon Corporation 2002-2009
 *   All rights reserved.
 *
 *   This file is Example Software as defined in the Software
 *   License Agreement that governs its use.
 *
 *   ECHELON MAKES NO REPRESENTATION, WARRANTY, OR CONDITION OF
 *   ANY KIND, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE OR IN
 *   ANY COMMUNICATION WITH YOU, INCLUDING, BUT NOT LIMITED TO,
 *   ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY
 *   QUALITY, FITNESS FOR ANY PARTICULAR PURPOSE, 
 *   NONINFRINGEMENT, AND THEIR EQUIVALENTS.
 */
#if !defined(DEFINED_SHORTSTACKDEV_C)
#define DEFINED_SHORTSTACKDEV_C

#include <string.h>
#include "ShortStackDev.h"
#include "ShortStackApi.h"

/*
 *  Self-identification data
 *  DO NOT EDIT
 */
static const unsigned char siData[] =
{
    0x00, 0x09, 0x00, 0x00, 0x00, 0x00, 0x7F, 0x00, 
    0x7F
};

/*
 *  Application initialization data
 *  DO NOT EDIT
 */
static const unsigned char appInitData[] =
{
    /* 16-bit application signature: */
    LON_APP_SIGNATURE/256u, LON_APP_SIGNATURE%256u,
    /* program Id: */
    0x90, 0x00, 0x33, 0x06, 0x00, 0x02, 0x04, 0x02, 
    /* communication parameters: */
    0x37, 0x2E, 0x16, 0x09, 0x1A, 0x2B, 0x2C, 0x00, 
    0x04, 0x00, 0xFC, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /* preferences */
    LON_EXPLICIT_ADDRESSING | LON_SERVICE_PIN_TIMER,
    /* number of static network variables: */
    0x00, 
    /* one configuration byte per network variable: */
};

/*
 * Constant: mtTable
 */
static const LonMtDescription mtTable[] =
{
    TRUE      /* tag only allows for explicit addressing */
}; /* end of MT table */

const unsigned char* LonGetSiData(unsigned* pLength)
{
    *pLength = (unsigned)sizeof(siData);
    return siData;
}

const unsigned char* LonGetAppInitData(void)
{
    return appInitData;
}

const LonNvDescription* const LonGetNvTable(void)
{
    return NULL;
}

const LonMtDescription* const LonGetMtTable(void)
{
    return mtTable;
}

#endif  /* defined(DEFINED_SHORTSTACKDEV_C) */
/* end of file. */
