/*  
 *   File: ShortStackDev.h
 *   Generated by LonTalk Interface Developer 4.00.11
 *
 *   Created on Thu Nov 13 09:55:48 2014
 *   This file applies to the device with program ID 90:00:33:06:00:02:04:02
 *
 *   Copyright (c) Echelon Corporation 2002-2009
 *   All rights reserved.
 *
 *   This file is Example Software as defined in the Software
 *   License Agreement that governs its use.
 *
 *   ECHELON MAKES NO REPRESENTATION, WARRANTY, OR CONDITION OF
 *   ANY KIND, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE OR IN
 *   ANY COMMUNICATION WITH YOU, INCLUDING, BUT NOT LIMITED TO,
 *   ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY
 *   QUALITY, FITNESS FOR ANY PARTICULAR PURPOSE, 
 *   NONINFRINGEMENT, AND THEIR EQUIVALENTS.
 */
#if !defined(DEFINED_SHORTSTACKDEV_H)
#define DEFINED_SHORTSTACKDEV_H

#include <stddef.h>
#include "LonPlatform.h"
#include "LonNvTypes.h"
#include "LonCpTypes.h"

/*
 *  Enumeration: LonNvIndex
 */
typedef LON_ENUM_BEGIN(LonNvIndex)
{
    LonNvCount = 0
} LON_ENUM_END(LonNvIndex);

#define LON_PERSISTENT_NVS  0

/*
 *  Enumeration: LonMtIndex
 */
typedef LON_ENUM_BEGIN(LonMtIndex)
{
    LonMtIndexIfsfNonbindMT = 0,
    LonMtIndexMyDummyTagNotB = 1,
    LonMtCount = 2
} LON_ENUM_END(LonMtIndex);


/*
 *  Application Buffer Sizes
 */

#define LON_APP_OUTPUT_BUFSIZE 66u
#define LON_APP_INPUT_BUFSIZE  66u
#define LON_ISI_ENABLED   0x20   /* 0x20: ISI API supported, 0x00 otherwise. Also enabled expl. addressing! */
#define LON_APP_SIGNATURE 1922u
#define LON_SERVICE_PIN_TIMER 0u
#define LON_EXPLICIT_ADDRESSING  (0x20|LON_ISI_ENABLED)    /* 0x20: enable expl. addressing (zero to disable) */

/*  The program ID for this device. Do not edit */
#define STD_PROGRAM_ID "90:00:33:06:00:02:04:02"

/*  Include support for Query* functions: */
#define LON_NM_QUERY_FUNCTIONS 1      /* include Query... functions */

/*  Include support for Update* functions: */
#define LON_NM_UPDATE_FUNCTIONS 1     /* include Update... functions */

/*   Include support for application messaging: */
#define LON_APPLICATION_MESSAGES  1    /* application messages are enabled */
#define LON_UTILITY_FUNCTIONS  1   /* control inclusion of utility functions (0,1) */
#define LON_FB_COUNT  0


/*  Size of the file access window in bytes (big-endian): */
#define LON_DMF_WINDOW_SIZE  0
#define LON_DMF_ENABLED  0

/*
 *   Some utilities used by the API:
 */

#define LON_APP_INIT_MSG_SIZE     28   /* size of the app init message */
#define LON_MAX_NVS_IN_NV_INIT    61   /* maximum number of nvs in one nv init message */
#define LON_NV_ESCAPE_SEQUENCE    63   /* escape code to denote a nv index >  62 */

/*
 *  Type: LonNvDescription
 *  Defines the structure of the nvTable variable.
 *
 *  The LonNvDescription defines the structure of the nvTable, which is
 *  implemented in ShortStackDev.c. 
 *  The nvTable is used by various API functions to obtain details
 *  for each individual network variable (configuration network 
 *  variables included). Each element of a network variable array
 *  has a separate record in this table.
 */
#define LON_NVDESC_OUTPUT_MASK        0x80u
#define LON_NVDESC_OUTPUT_SHIFT       7
#define LON_NVDESC_OUTPUT_FIELD       Attributes

#define LON_NVDESC_PERSISTENT_MASK    0x40u
#define LON_NVDESC_PERSISTENT_SHIFT   6
#define LON_NVDESC_PERSISTENT_FIELD   Attributes

#define LON_NVDESC_POLLED_MASK        0x20u
#define LON_NVDESC_POLLED_SHIFT       5
#define LON_NVDESC_POLLED_FIELD       Attributes

#define LON_NVDESC_SYNC_MASK          0x10u
#define LON_NVDESC_SYNC_SHIFT         4
#define LON_NVDESC_SYNC_FIELD         Attributes

#define LON_NVDESC_CHANGEABLE_MASK    0x08u
#define LON_NVDESC_CHANGEABLE_SHIFT   3
#define LON_NVDESC_CHANGEABLE_FIELD   Attributes

typedef struct 
{
    volatile void* const pData;  /* pointer to network variable data   */
    unsigned char DeclaredSize;        /* declared, initial and maximum size */
    unsigned char Attributes;          /* See macro definitions above        */
} LonNvDescription;

/*
 *  Message Tag Table Type Definition
 */
typedef LonBool LonMtDescription;

/*
 *  Prototypes for access functions:
 */
extern const unsigned char* LonGetSiData(unsigned* pLength);
extern const unsigned char* LonGetAppInitData(void);
extern const LonNvDescription* const LonGetNvTable(void);
extern const LonMtDescription* const LonGetMtTable(void);

#endif  /* defined(DEFINED_SHORTSTACKDEV_H) */
/* end of file. */
