/*
 * Filename: ShortStackIsiTypes.h
 *
 * Description: This file contains type definitions related to 
 * Interoperable Self-Installation (ISI).
 *
 * Copyright (c) Echelon Corporation 2008-2009.  All rights reserved.
 *
 * This file is ShortStack LonTalk Compact API Software as defined in the 
 * Software License Agreement that governs its use.
 *
 * ECHELON MAKES NO REPRESENTATION, WARRANTY, OR CONDITION OF
 * ANY KIND, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE OR IN
 * ANY COMMUNICATION WITH YOU, INCLUDING, BUT NOT LIMITED TO,
 * ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY
 * QUALITY, FITNESS FOR ANY PARTICULAR PURPOSE, 
 * NONINFRINGEMENT, AND THEIR EQUIVALENTS.
 */

#ifndef SHORTSTACK_ISI_TYPES_H
#define SHORTSTACK_ISI_TYPES_H

/*
 * *****************************************************************************
 * TITLE: SHORTSTACK ISI TYPES
 * *****************************************************************************
 *
 * Definitions of the enumerations and data types required by the Interoperable 
 * Self-Installation (ISI) portion of the ShortStack LonTalk Compact API.
 */

/*
 * Note this file is best included through ShortStackDev.h, which is generated by the 
 * LonTalk Interface Developer.
*/

#include "ShortStackTypes.h"

/*
 * Basic ISI API macros
 */
#define ISI_DEFAULT_GROUP   128u
#define ISI_NO_ASSEMBLY     255u
#define ISI_NO_INDEX        255u

/* 
 *  Enumeration: IsiEvent
 *  Enumeration for different event types.
 *
 *  This enumeration represents the possible events that are passed to the 
 *  host when the ISI engine does a callback.
 */
typedef enum IsiEvent
{
    IsiNormal           = 0,
    IsiRun              = 1,
    IsiPending          = 2,
    IsiApproved         = 3,
    IsiImplemented      = 4,
    IsiCancelled        = 5,
    IsiDeleted          = 6,
    IsiWarm             = 7,
    IsiPendingHost      = 8,
    IsiApprovedHost     = 9,
    IsiAborted          = 10,
    IsiRetry            = 11,
    IsiWink             = 12,
    IsiRegistered       = 13
} IsiEvent;

/* 
 *  Enumeration: IsiType
 *  Enumeration for different engine types.
 *
 *  This enumeration specifies the ISI protocol to be implemented by the ISI
 *  engine.
 */
typedef enum IsiType
{
    IsiTypeS,                       /* Use for ISI-S and ISI-S/C */
    IsiTypeDa,                      /* Use for Isi-DA and Isi-DA/C */
    IsiTypeDas                      /* Use for ISI-DAS and ISI-DAS/C */
} IsiType;

/* 
 *  Enumeration: IsiStartFlags
 *  Enumeration for option flags used while starting the ISI engine.
 *
 *  This enumeration represents option flags for the <IsiStart> function used to 
 *  start the ISI engine. Use a combination of these flags with the <IsiStart> function.
 */
typedef enum IsiStartFlags
{
    IsiFlagNone                 = 0,    /* Does nothing */
    IsiFlagExtended             = 1,    /* Enables use of extended DRUM and enrollment messages */
    IsiFlagHeartbeat            = 2,    /* Enables ISI NV heartbeats */
    IsiFlagApplicationPeriodic  = 4,    /* Enables IsiApplicationPeriodic() */
    IsiFlagSupplyDiagnostics    = 8     /* Enables UpdateDiagnostics callback */
} IsiStartFlags;

/* 
 *  Enumeration: IsiDirection
 *  Enumeration for the direction of a network variable in a connection.
 *
 *  This enumeration represents the direction of the network variable
 *  on offer in a CSMO.
 */
typedef enum IsiDirection
{
    IsiDirectionOutput          = 0,    
    IsiDirectionInput           = 1,    
    IsiDirectionAny             = 2,    
    IsiDirectionVarious         = 3
} IsiDirection;

/* 
 *  Enumeration: IsiScope
 *  Enumeration for scope of a connection message.
 *
 *  This enumeration represents the different values that can be used in
 *  the scope field of a CSMO message. This value represents the scope of the
 *  resource file containing the functional profile and network variable type
 *  definitions specified by the Profile and NvType fields.
 */
typedef enum IsiScope
{
    IsiScopeStandard            = 0,    
    IsiScopeManufacturer        = 3
} IsiScope;

/*
 *  Typedef: IsiConnectionId
 *  Structure representing the unique connection ID.
 *
 *  This structure contains the unique connection ID for a connection.
 */
typedef struct IsiConnectionId
{
    /* A unique identifier for the connection host, based on the host’s unique ID. */
    unsigned char         UniqueId[LON_UNIQUE_ID_LENGTH - 1]; 
    /* Connection host-allocated serial number.*/
    short int         SerialNumber;                       
} IsiConnectionId;

/*
 *  Typedef: IsiConnectionHeader
 *  Structure representing the connection header.
 *
 *  Following the ISI Message Header, all connection-related messages start with
 *  this structure.
 */
typedef struct IsiConnectionHeader
{
    /* See <IsiConnectionId>. */
    IsiConnectionId     ConnectionId;
    /* Selector value 0 – 0x2FFF. The most significant 2 bits must be cleared 
       and are reserved for future extension. */
    short int             Selector;
} IsiConnectionHeader;

/*
 *  Typedef: IsiConnection
 *  Structure representing a row in the connection table.
 *
 *  This structure is used to represent a row in the connection table that
 *  is returned by <IsiGetConnection> and is used in <IsiSetConnection> to set a
 *  row in the table.
 */

/*
 * Use the ISI_CONN_STATE_* macros to access the State field in IsiConnection.Attributes1
 */
#define ISI_CONN_STATE_MASK     0xC0
#define ISI_CONN_STATE_SHIFT    6
#define ISI_CONN_STATE_FIELD    Attributes1

 /*
 * Use the ISI_CONN_EXTEND_* macros to access the Extend field in IsiConnection.Attributes1
 */
#define ISI_CONN_EXTEND_MASK    0x20
#define ISI_CONN_EXTEND_SHIFT   5
#define ISI_CONN_EXTEND_FIELD   Attributes1

/*
 * Use the ISI_CONN_CSME_* macros to access the State field in IsiConnection.Attributes1
 */
#define ISI_CONN_CSME_MASK      0x10
#define ISI_CONN_CSME_SHIFT     4
#define ISI_CONN_CSME_FIELD Attributes1

/*
 * Use the ISI_CONN_WIDTH_* macros to access the State field in IsiConnection.Attributes1
 */
#define ISI_CONN_WIDTH_MASK     0x0F
#define ISI_CONN_WIDTH_SHIFT    0
#define ISI_CONN_WIDTH_FIELD    Attributes1

/*
 * Use the ISI_CONN_OFFSET_* macros to access the Auto field in IsiConnection.Attributes2
 */
#define ISI_CONN_OFFSET_MASK    0xFC
#define ISI_CONN_OFFSET_SHIFT   2
#define ISI_CONN_OFFSET_FIELD   Attributes2

/*
 * Use the ISI_CONN_AUTO_* macros to access the Auto field in IsiConnection.Attributes2
 */
#define ISI_CONN_AUTO_MASK      0x02
#define ISI_CONN_AUTO_SHIFT     1
#define ISI_CONN_AUTO_FIELD     Attributes2

typedef struct IsiConnection
{
    IsiConnectionHeader Header;
    unsigned char     Host;
    unsigned char     Member;
    unsigned char     Attributes1;    /* contains state, extend, csme, width. See ISI_CONN_STATE_*, _EXTEND_*, _CSME_* and _WIDTH_* macros */
    unsigned char     Attributes2;    /* contains offset, auto. See ISI_CONN_OFFSET_* and _AUTO_* macros */
} IsiConnection;

/*
 *  Typedef: IsiCsmoData
 *  Structure representing the CSMO message.
 *
 *  This structure contains the fields of a CSMO message to be sent by the
 *  ISI engine.
 */

/*
 * Use the ISI_CSMO_DIR_* macros to access the Direction field in IsiCsmoData.Attributes1
 */
#define ISI_CSMO_DIR_MASK       0xC0
#define ISI_CSMO_DIR_SHIFT      6
#define ISI_CSMO_DIR_FIELD      Attributes1

/*
 * Use the ISI_CSMO_WIDTH_* macros to access the Width field in IsiCsmoData.Attributes1
 */
#define ISI_CSMO_WIDTH_MASK     0x3F
#define ISI_CSMO_WIDTH_SHIFT    0
#define ISI_CSMO_WIDTH_FIELD    Attributes1

/*
 * Use the ISI_CSMO_ACK_* macros to access the Acknowledged field in IsiCsmoData.Attributes2
 */
#define ISI_CSMO_ACK_MASK       0x80
#define ISI_CSMO_ACK_SHIFT      7
#define ISI_CSMO_ACK_FIELD      Attributes2

/*
 * Use the ISI_CSMO_POLL_* macros to access the Poll field in IsiCsmoData.Attributes2
 */
#define ISI_CSMO_POLL_MASK      0x40
#define ISI_CSMO_POLL_SHIFT     6
#define ISI_CSMO_POLL_FIELD     Attributes2

/*
 * Use the ISI_CSMO_SCOPE_* macros to access the Scope field in IsiCsmoData.Attributes2
 */
#define ISI_CSMO_SCOPE_MASK     0x30
#define ISI_CSMO_SCOPE_SHIFT    4
#define ISI_CSMO_SCOPE_FIELD    Attributes2

typedef struct IsiCsmoData
{
    /* The group (or: device category) that this connection applies to. */
    unsigned char     Group;
    unsigned char     Attributes1;    /* contains Direction, Width. See ISI_CSMO_DIR_* and _WIDTH_* macros */
    /* Functional profile number of the functional profile that defines the 
       functional block containing this input or output, or zero if none. */
    short int     Profile;
    /* NV type index of the NV type for the network variable, or zero if none
       specified. The NV type index is an index into resource file that defines the
       network variable type for the network variable on offer. */
    unsigned char     NvType;
    /* Variant number for the offered network variable. Variants can be defined for
       any functional profile/member number pair. */
    unsigned char     Variant;
    struct Extended 
    {
        unsigned char     Attributes2;    /* contains Ack, Poll, Scope. See ISI_CSMO_ACK_*, _POLL_* and _SCOPE_* macros */
        /* The first 6 bytes of the connection host’s standard program ID. 
           The last two standard program ID bytes (channel type and model
           number) are not included. */
        unsigned char     Application[LON_PROGRAM_ID_LENGTH - 2];
        /* NV member number within the functional block, or zero if none. */
        unsigned char     Member;
    } Extended;    
} IsiCsmoData;

/*
 * This flag determines whether a message is supposed to be responded to.
 */
#define IsiRpcUnacknowledged        ((signed) 0x80)

/* 
 *  Enumeration: IsiDownlinkRpcCode
 *  Codes for downlink calls from the host to the Micro Server.
 *
 *  These are the function identifiers for downlink API calls.
 *  Numbers are assigned explicitly just to indicate the import
 *  of maintaining certain number values as these must be consistent
 *  with the Micro Server's implementation.
 */
typedef enum IsiDownlinkRpcCode
{
    IsiRpcStop                      = 0,
    IsiRpcStart                     = 1,
    IsiRpcReturnToFactoryDefaults   = 2,
    IsiRpcAcquireDomain             = 3,
    IsiRpcStartDeviceAcquisition    = 4,
    IsiRpcOpenEnrollment            = 5,
    IsiRpcCreateEnrollment          = 6,
    IsiRpcExtendEnrollment          = 7,
    IsiRpcCancelEnrollment          = 8,
    IsiRpcLeaveEnrollment           = 9,
    IsiRpcDeleteEnrollment          = 10,
    IsiRpcInitiateAutoEnrollment    = 11,
    IsiRpcIsConnected               = 12,
    IsiRpcImplementationVersion     = 13,
    IsiRpcProtocolVersion           = 14,
    IsiRpcIsBecomingHost            = 15,
    IsiRpcIsRunning                 = 16,
    IsiRpcCancelAcquisition         = 17,
    IsiRpcFetchDevice               = 18,        
    IsiRpcFetchDomain               = 19,
    IsiRpcIssueHeartbeat            = 20
} IsiDownlinkRpcCode;

/* 
 *  Enumeration: IsiUplinkRpcCode
 *  Codes for uplink callbacks from the Micro Server to the host.
 *
 *  These are the callback identifiers for uplink API calls.
 *  Numbers are assigned explicitly just to indicate the import
 *  of maintaining certain number values as these must be consistent
 *  with the Micro Server's implementation.
 */
typedef enum IsiUplinkRpcCode
{
    IsiRpcCreatePeriodicMsg         = 0,
    IsiRpcUpdateUserInterface       = 1  | IsiRpcUnacknowledged,
    IsiRpcCreateCsmo                = 2,
    IsiRpcGetPrimaryGroup           = 3,
    IsiRpcGetAssembly               = 4,
    IsiRpcGetNextAssembly           = 5,
    IsiRpcGetNvIndex                = 6,
    IsiRpcGetNextNvIndex            = 7,
    IsiRpcGetPrimaryDid             = 8,
    IsiRpcGetWidth                  = 9,
    IsiRpcGetNvValue                = 10,
    IsiRpcGetConnTabSize            = 11,
    IsiRpcGetConnection             = 12,
    IsiRpcSetConnection             = 13 | IsiRpcUnacknowledged,
    IsiRpcQueryHeartbeat            = 14,
    IsiRpcGetRepeatCount            = 15,
    IsiRpcUserCommand               = 64
} IsiUplinkRpcCode;

/*
 *  Typedef: IsiRpcMessage
 *  Structure defining the data format in the RPC messages between the host and the Micro Server.
 *
 *  This structure defines the format of the data in the ISI remote procedure call messages.
 */
typedef struct IsiRpcMessage
{
    LonSmipHdr  Header;         /* Message header, where command can be one of IsiCmd, IsiAck, IsiNack */
    unsigned char     RpcCode;        /* RPC Function Code */
    unsigned char     SequenceNumber; /* A sequence number for correlation */
    unsigned char     Parameters[2];  /* Two 1-byte parameters */ 
    struct RpcData 
    {
        unsigned char Length;         /* Length of the complete RpcData structure */
        unsigned char Data[31];       /* Contains data like IsiCsmoData, IsiConnection and so on. */
    } RpcData; 
} IsiRpcMessage;

#define IsiRpcMessageLength(p)  ((unsigned char)((sizeof(IsiRpcMessage) - 2 - sizeof(((IsiRpcMessage*)0)->RpcData.Data) + (p)->RpcData.Length)))

#endif /* SHORTSTACK_ISI_TYPES_H */
