/* This file was created by WHPCVT.EXE. DO NOT MODIFY BY HAND! */

#define Adding_a_Target                                   	23
#define Adding_Resources_to_a_Target                      	59
#define Adding_Source_Files                               	34
#define Auto_Refresh                                      	55
#define Closing_a_Project                                 	18
#define Configuring_the_Integrated_Development_Environment	52
#define DOS_M_16Mbit_Targets                              	65
#define DOS_M_32Mbit_Targets                              	66
#define Editing_the_Source_File                           	44
#define Executing_Special_Commands                        	58
#define The_Files_the_Integrated_Development_Environment_Uses	6
#define Getting_Help                                      	43
#define Getting_Started_with_a_Short_Tutorial             	13
#define How_the_Environment_Operates                      	4
#define How_the_Integrated_Development_Environment_Looks  	5
#define The_IDE_Menu_Bar                                  	10
#define The_IDE_Status_Bar                                	11
#define The_IDE_Switches                                  	46
#define The_IDE_Toolbar                                   	12
#define Including_Libraries_in_a_Target                   	60
#define Index_of_Topics                                   	1
#define Invoking_DOS_Applications_from_the_IDE_under_OSD2 	71
#define Invoking_Other_Applications_from_the_IDE          	70
#define Linux_Targets                                     	69
#define Making_Source_Files                               	38
#define Making_Targets                                    	28
#define Marking_a_Source_File_for_Remake                  	37
#define Marking_a_Target_for_Remake                       	27
#define Minimizing_a_Target                               	24
#define The_Open_Watcom_IDE_Project_Window                	16
#define Open_Watcom_Integrated_Development_Environment    	3
#define Opening_a_Project                                 	17
#define OSD2_M_16Mbit_Targets                             	67
#define OSD2_M_32Mbit_Targets                             	68
#define Other_Run_Functions                               	31
#define Quitting_the_Open_Watcom_Integrated_Development_Environment	9
#define Removing_a_Source_File                            	35
#define Removing_a_Target                                 	25
#define Renaming_a_Source_File                            	36
#define Renaming_a_Target                                 	26
#define Review_of_What_Happened                           	15
#define Running_a_Target                                  	30
#define Saving_a_Project                                  	19
#define Saving_the_Log                                    	45
#define Saving_the_Project_Under_a_New_Name               	21
#define Selecting_a_Source_Revision_Control_System        	57
#define Selecting_Your_Own_Text_Editor                    	56
#define Setting_Application_Parameters                    	32
#define Setting_Source_File_Switches                      	50
#define Setting_Target_and_Source_File_Switches           	48
#define Setting_Target_Switches                           	49
#define Show_Status_Bar                                   	54
#define Show_Toolbar                                      	53
#define A_Simple_Executable                               	14
#define Starting_the_Open_Watcom_Integrated_Development_Environment	8
#define Stopping_the_Make_Function                        	42
#define Table_of_Contents                                 	2
#define Targets_and_Image_Types_Supported_by_the_IDE      	61
#define Updating_the_Project                              	20
#define Using_Release_and_Development_Switches            	47
#define Using_the_Autodepend_Switch                       	51
#define Using_the_IDE_Log_Window                          	41
#define Using_the_Information_of_the_IDE_from_outside     	72
#define Using_the_Open_Watcom_Integrated_Development_Environment	7
#define Viewing_Included_Files                            	40
#define Viewing_the_Make_Command_for_a_Source_File        	39
#define Viewing_the_Make_Command_for_a_Target             	29
#define Win16_Targets                                     	63
#define Win32_Targets                                     	62
#define Win386_LWatcom_ExtenderR_Targets                  	64
#define Working_with_Source_Files                         	33
#define Working_with_Targets                              	22
