/* This file was created by WHPCVT.EXE. DO NOT MODIFY BY HAND! */

#define Adding_a_Module_File                              	13
#define AutoMarranging_of_Graph_Views                     	42
#define Automatically_Saving_Options_on_Exit              	47
#define Browser_Files                                     	8
#define The_Browser_Menu_Bar                              	7
#define Changing_the_Graph_Orientation                    	44
#define The_Class_Inheritance_View                        	19
#define Collapsing_Nodes                                  	24
#define Configuring_the_Browser                           	35
#define Creating_a_Browser_Database_File_from_the_Command_Line	10
#define Creating_a_Browser_Database_File_within_the_Browser	9
#define Defining_Graph_View_Legends                       	45
#define Disabling_a_Module_File                           	15
#define Enabling_a_Module_File                            	16
#define Enumerator_Styles                                 	40
#define Expanding_Nodes                                   	23
#define Find                                              	30
#define Find_Filters                                      	32
#define Find_Pattern                                      	31
#define Find_Selected                                     	34
#define The_Function_Call_Tree_View                       	20
#define Global_Symbol_Queries                             	37
#define Global_Views                                      	17
#define Goto_Definition                                   	26
#define Index_of_Topics                                   	1
#define Line_Drawing_Method_for_Graph_Views               	43
#define The_List_View                                     	18
#define Loading_Options                                   	48
#define Locating_Symbols                                  	29
#define Manipulating_the_Tree_Views                       	21
#define Member_Filters_for_Classes                        	41
#define The_Open_Watcom_Browser                           	3
#define Opening_an_Existing_Browser_Database_File         	11
#define Performing_the_Find                               	33
#define Query_Filters                                     	39
#define Query_Pattern                                     	38
#define Quitting_the_Browser                              	6
#define Regular_Expressions_for_Find_and_Query            	36
#define Removing_a_Module_File                            	14
#define Saving_Options                                    	49
#define Selecting_a_Text_Editor                           	46
#define Selecting_Root_Nodes                              	22
#define Setting_Source_Search_Paths                       	50
#define Source_References                                 	27
#define Starting_the_Browser                              	5
#define Symbol_References                                 	28
#define Table_of_Contents                                 	2
#define Using_the_Browser                                 	4
#define Viewing_Detail_Information                        	25
#define Working_with_Browser_Module_Files                 	12
