copy rdos.cfg rdos
copy ..\..\kernel\os\kernel.exe rdos
copy ..\..\kernel\os\longmode.bin rdos
copy ..\..\kernel\os\sched.rdv rdos
copy ..\..\kernel\os\task.rdv rdos
copy ..\..\kernel\freetype\freetype.rdv rdos
copy ..\..\kernel\os\util.rdv rdos
copy ..\..\kernel\acpi\acpi.rdv rdos
copy ..\..\kernel\os\fs.rdv rdos
copy ..\..\kernel\os\inifile.rdv rdos
copy ..\..\kernel\os\drive.rdv rdos
copy ..\..\kernel\os\fat.rdv rdos
copy ..\..\kernel\os\exec.rdv rdos
copy ..\..\kernel\os\pe.rdv rdos
copy ..\..\kernel\os\audio.rdv rdos
copy ..\..\kernel\os\com.rdv rdos
copy ..\..\kernel\os\carddev.rdv rdos
copy ..\..\kernel\os\printer.rdv rdos
copy ..\..\kernel\os\net.rdv rdos
copy ..\..\kernel\os\ip.rdv rdos
copy ..\..\kernel\os\ipc.rdv rdos
copy ..\..\kernel\os\lon.rdv rdos
copy ..\..\kernel\os\tlist.rdv rdos
copy ..\..\kernel\os\wd.rdv rdos
copy ..\..\kernel\os\guidev.rdv rdos
copy ..\..\kernel\os\realtime.rdv rdos
copy ..\..\kernel\bios\pcbios.rdv rdos
copy ..\..\kernel\debug\kdebug.rdv rdos
copy ..\..\kernel\debug\pcshut.exe rdos
copy ..\..\kernel\bios\vga.rdv rdos
copy ..\..\kernel\dosemu\emulate.rdv rdos
copy ..\..\kernel\pcdev\pic.rdv rdos
copy ..\..\kernel\pcdev\apic.rdv rdos
copy ..\..\kernel\pcdev\rtc.rdv rdos
copy ..\..\kernel\pcdev\pci.rdv rdos
copy ..\..\kernel\pcdev\pnp.rdv rdos
copy ..\..\kernel\pcdev\keymap.rdv rdos
copy ..\..\kernel\pcdev\ps2key.rdv rdos
copy ..\..\kernel\pcdev\ps2keym.rdv rdos
copy ..\..\kernel\pcdev\ac97.rdv rdos
copy ..\..\kernel\pcdev\ide.rdv rdos
copy ..\..\kernel\pcdev\floppy.rdv rdos
copy ..\..\kernel\pcdev\ahci.rdv rdos
copy ..\..\kernel\pcdev\sdcard.rdv rdos
copy ..\..\kernel\pcdev\stdcom.rdv rdos
copy ..\..\kernel\pcdev\can.rdv rdos
copy ..\..\kernel\usbdev\usb.rdv rdos
copy ..\..\kernel\usbdev\ohci.rdv rdos
copy ..\..\kernel\usbdev\uhci.rdv rdos
copy ..\..\kernel\usbdev\ehci.rdv rdos
copy ..\..\kernel\usbdev\xhci.rdv rdos
copy ..\..\kernel\usbdev\hub.rdv rdos
copy ..\..\kernel\usbdev\hid.rdv rdos
copy ..\..\kernel\usbdev\hidcard.rdv io
copy ..\..\kernel\usbdev\usbcdc.rdv rdos
copy ..\..\kernel\usbdev\usbcom.rdv rdos
copy ..\..\kernel\usbdev\usbcan.rdv rdos
copy ..\..\kernel\usbdev\usbdisc.rdv rdos
copy ..\..\kernel\printdev\kr203.rdv rdos
copy ..\..\kernel\touchdev\dmc6000.rdv rdos
copy ..\..\kernel\touchdev\egalax.rdv rdos
copy ..\..\kernel\audiodev\cs5536a.rdv rdos
copy ..\..\kernel\audiodev\hda.rdv rdos
copy ..\..\kernel\netdev\rtl8139.rdv rdos
copy ..\..\kernel\netdev\rtl8169.rdv rdos
copy \rdosdev\src\power.rdv power
copy \rdosdev\src\nopower.rdv power
copy \rdosdev\src\ioe.rdv io
copy \rdosdev\src\itc.rdv io
copy \rdosdev\src\pem.rdv power
copy \rdosdev\src\cancom.rdv rdos
copy \rdosdev\src\ioe2.rdv io
copy \rdosdev\src\ioekey.rdv io
copy ..\..\apps\freecom\command.exe rdos
copy ..\..\apps\ftpd\ftpd.exe rdos
copy ..\..\apps\tcpwd\tcpwd.exe rdos
copy ..\..\apps\mbedit\ed.exe rdos
