copy rdos.cfg files
copy ..\..\kernel\os\kernel.exe files
copy ..\..\kernel\os\longmode.bin files
copy ..\..\kernel\os\sched.rdv files
copy ..\..\kernel\os\task.rdv files
copy ..\..\kernel\freetype\freetype.rdv files
copy ..\..\kernel\os\util.rdv files
copy ..\..\kernel\acpi\acpi.rdv files
copy ..\..\kernel\os\fs.rdv files
copy ..\..\kernel\os\inifile.rdv files
copy ..\..\kernel\os\drive.rdv files
copy ..\..\kernel\os\fat.rdv files
copy ..\..\kernel\os\exec.rdv files
copy ..\..\kernel\os\pe.rdv files
copy ..\..\kernel\os\audio.rdv files
copy ..\..\kernel\os\com.rdv files
copy ..\..\kernel\os\carddev.rdv files
copy ..\..\kernel\os\printer.rdv files
copy ..\..\kernel\os\net.rdv files
copy ..\..\kernel\os\ip.rdv files
copy ..\..\kernel\os\ipc.rdv files
copy ..\..\kernel\os\lon.rdv files
copy ..\..\kernel\os\tlist.rdv files
copy ..\..\kernel\os\wd.rdv files
copy ..\..\kernel\os\guidev.rdv files
copy ..\..\kernel\os\realtime.rdv files
copy ..\..\kernel\bios\pcbios.rdv files
copy ..\..\kernel\debug\kdebug.rdv files
copy ..\..\kernel\debug\pcshut.exe files
copy ..\..\kernel\bios\vga.rdv files
copy ..\..\kernel\dosemu\emulate.rdv files
copy ..\..\kernel\dosemu\dos.rdv files
copy ..\..\kernel\dosemu\dpmi.rdv files
copy ..\..\kernel\pcdev\rtc.rdv files
copy ..\..\kernel\pcdev\pnp.rdv files
copy ..\..\kernel\pcdev\keymap.rdv files
copy ..\..\kernel\pcdev\ps2key.rdv files
copy ..\..\kernel\pcdev\ps2keym.rdv files
copy ..\..\kernel\pcdev\ac97.rdv files
copy ..\..\kernel\pcdev\ide.rdv files
copy ..\..\kernel\pcdev\floppy.rdv files
copy ..\..\kernel\pcdev\ahci.rdv files
copy ..\..\kernel\pcdev\nvme.rdv files
copy ..\..\kernel\pcdev\sdcard.rdv files
copy ..\..\kernel\pcdev\stdcom.rdv files
copy ..\..\kernel\pcdev\can.rdv files
copy ..\..\kernel\pcdev\mcan.rdv files
copy ..\..\kernel\fs\vfs.rdv files
copy ..\..\kernel\usbdev\usb.rdv files
copy ..\..\kernel\usbdev\ohci.rdv files
copy ..\..\kernel\usbdev\uhci.rdv files
copy ..\..\kernel\usbdev\ehci.rdv files
copy ..\..\kernel\usbdev\xhci.rdv files
copy ..\..\kernel\usbdev\hub.rdv files
copy ..\..\kernel\usbdev\hid.rdv files
copy ..\..\kernel\usbdev\hidcard.rdv files
copy ..\..\kernel\usbdev\usbcdc.rdv files
copy ..\..\kernel\usbdev\usbcom.rdv files
copy ..\..\kernel\usbdev\usbcan.rdv files
copy ..\..\kernel\usbdev\usbdisc.rdv files
copy ..\..\kernel\usbdev\usbvfs.rdv files
copy ..\..\kernel\printdev\kr203.rdv files
copy ..\..\kernel\printdev\pmu.rdv files
copy ..\..\kernel\printdev\ttp.rdv files
copy ..\..\kernel\touchdev\dmc6000.rdv files
copy ..\..\kernel\touchdev\egalax.rdv files
copy ..\..\kernel\audiodev\cs5536a.rdv files
copy ..\..\kernel\audiodev\hda.rdv files
copy ..\..\kernel\netdev\rtl8139.rdv files
copy ..\..\kernel\netdev\rtl8169.rdv files
copy ..\..\kernel\netdev\i2xx.rdv files
copy \rdos-uacpi\rdos\uacpi.exe files
copy ..\..\kernel\fs\parttool.exe files
copy ..\..\kernel\fs\fat.exe files
copy ..\..\kernel\ssl\ssl.rdv files
copy ..\..\kernel\ssl\sslserv.exe files
copy \rdosdev\src\power.rdv files
copy \rdosdev\src\nopower.rdv files
copy \rdosdev\src\preem.rdv files
copy \rdosdev\src\ioe.rdv files
copy \rdosdev\src\itc.rdv files
copy \rdosdev\src\ehl5.rdv files
copy \rdosdev\src\pem.rdv files
copy \rdosdev\src\cancom.rdv files
copy \rdosdev\src\ioe2.rdv files
copy \rdosdev\src\ioekey.rdv files
copy ..\..\apps\freecom\command.exe files
copy ..\..\apps\ftpd\ftpd.exe files
copy ..\..\apps\tcpwd\tcpwd.exe files
copy ..\..\apps\mbedit\ed.exe files
