module daq2_app
(
  input                   clk,
  input                   reset,

  input                   rx_ref_clk,
  input                   rx_sysref,
  output                  rx_sync,
  input       [ 3:0]      rx_data_p,
  input       [ 3:0]      rx_data_n,

  input                   tx_ref_clk,
  input                   tx_sysref,
  input                   tx_sync,
  output      [ 3:0]      tx_data_p,
  output      [ 3:0]      tx_data_n,

  input                   trig,

  inout                   adc_fdb,
  inout                   adc_fda,
  inout                   dac_irq,
  inout       [ 1:0]      clkd_status,

  inout                   adc_pd,
  inout                   dac_txen,
  inout                   dac_reset,
  inout                   clkd_sync,

  output     [3:0]        rx_pll_locked,
  output     [3:0]        tx_pll_locked
);

 wire [31:0]              rx_data_0;
 wire [31:0]              rx_data_1;
 wire [31:0]              rx_data_2;
 wire [31:0]              rx_data_3;

 wire                     rx_clk;
 wire                     tx_clk;

ila_6 your_instance_name (
	.clk(rx_clk), // input wire clk

	.probe0(rx_pll_locked[0]), // input wire [0:0]  probe0  
	.probe1(rx_pll_locked[1]), // input wire [0:0]  probe0  
	.probe2(rx_pll_locked[2]), // input wire [0:0]  probe0  
	.probe3(rx_pll_locked[3]), // input wire [0:0]  probe0  
	.probe4(rx_data_0), // input wire [31:0]  probe8 
	.probe5(rx_data_1), // input wire [31:0]  probe9 
	.probe6(rx_data_2), // input wire [31:0]  probe10 
	.probe7(rx_data_3) // input wire [31:0]  probe11
);

  system_util_daq2_xcvr_0 util_daq2_xcvr
       (.cpll_ref_clk_0(rx_ref_clk),
        .cpll_ref_clk_1(rx_ref_clk),
        .cpll_ref_clk_2(rx_ref_clk),
        .cpll_ref_clk_3(rx_ref_clk),
        .qpll_ref_clk_0(tx_ref_clk),
        .rx_0_n(rx_data_n[0]),
        .rx_0_p(rx_data_p[0]),
        .rx_1_n(rx_data_n[1]),
        .rx_1_p(rx_data_p[1]),
        .rx_2_n(rx_data_n[2]),
        .rx_2_p(rx_data_p[2]),
        .rx_3_n(rx_data_n[3]),
        .rx_3_p(rx_data_p[3]),
        .rx_calign_0(0),
        .rx_calign_1(0),
        .rx_calign_2(0),
        .rx_calign_3(0),
        .rx_charisk_0(),
        .rx_charisk_1(),
        .rx_charisk_2(),
        .rx_charisk_3(),
        .rx_clk_0(rx_clk),
        .rx_clk_1(rx_clk),
        .rx_clk_2(rx_clk),
        .rx_clk_3(rx_clk),
        .rx_data_0(rx_data0),
        .rx_data_1(rx_data1),
        .rx_data_2(rx_data2),
        .rx_data_3(rx_data3),
        .rx_disperr_0(),
        .rx_disperr_1(),
        .rx_disperr_2(),
        .rx_disperr_3(),
        .rx_notintable_0(),
        .rx_notintable_1(),
        .rx_notintable_2(),
        .rx_notintable_3(),
        .rx_out_clk_0(rx_clk),
        .tx_0_n(tx_data_n[0]),
        .tx_0_p(tx_data_p[0]),
        .tx_1_n(tx_data_n[1]),
        .tx_1_p(tx_data_p[1]),
        .tx_2_n(tx_data_n[2]),
        .tx_2_p(tx_data_p[2]),
        .tx_3_n(tx_data_n[3]),
        .tx_3_p(tx_data_p[3]),
        .tx_charisk_0(0),
        .tx_charisk_1(0),
        .tx_charisk_2(0),
        .tx_charisk_3(0),
        .tx_clk_0(tx_clk),
        .tx_clk_1(tx_clk),
        .tx_clk_2(tx_clk),
        .tx_clk_3(tx_clk),
        .tx_data_0(0),
        .tx_data_1(0),
        .tx_data_2(0),
        .tx_data_3(0),
        .tx_out_clk_0(tx_clk),
        .up_clk(clk),
        .up_cm_addr_0(0),
        .up_cm_enb_0(0),
        .up_cm_rdata_0(),
        .up_cm_ready_0(),
        .up_cm_wdata_0(0),
        .up_cm_wr_0(0),
        .up_cpll_rst_0(0),
        .up_cpll_rst_1(0),
        .up_cpll_rst_2(0),
        .up_cpll_rst_3(0),
        .up_es_addr_0(0),
        .up_es_addr_1(0),
        .up_es_addr_2(0),
        .up_es_addr_3(0),
        .up_es_enb_0(0),
        .up_es_enb_1(0),
        .up_es_enb_2(0),
        .up_es_enb_3(0),
        .up_es_rdata_0(),
        .up_es_rdata_1(),
        .up_es_rdata_2(),
        .up_es_rdata_3(),
        .up_es_ready_0(),
        .up_es_ready_1(),
        .up_es_ready_2(),
        .up_es_ready_3(),
        .up_es_reset_0(0),
        .up_es_reset_1(0),
        .up_es_reset_2(0),
        .up_es_reset_3(0),
        .up_es_wdata_0(0),
        .up_es_wdata_1(0),
        .up_es_wdata_2(0),
        .up_es_wdata_3(0),
        .up_es_wr_0(0),
        .up_es_wr_1(0),
        .up_es_wr_2(0),
        .up_es_wr_3(0),
        .up_qpll_rst_0(0),
        .up_rstn(!reset),
        .up_rx_addr_0(0),
        .up_rx_addr_1(0),
        .up_rx_addr_2(0),
        .up_rx_addr_3(0),
        .up_rx_enb_0(0),
        .up_rx_enb_1(0),
        .up_rx_enb_2(0),
        .up_rx_enb_3(0),
        .up_rx_lpm_dfe_n_0(1),
        .up_rx_lpm_dfe_n_1(1),
        .up_rx_lpm_dfe_n_2(1),
        .up_rx_lpm_dfe_n_3(1),
        .up_rx_out_clk_sel_0(0),
        .up_rx_out_clk_sel_1(0),
        .up_rx_out_clk_sel_2(0),
        .up_rx_out_clk_sel_3(0),
        .up_rx_pll_locked_0(rx_pll_locked[0]),
        .up_rx_pll_locked_1(rx_pll_locked[1]),
        .up_rx_pll_locked_2(rx_pll_locked[2]),
        .up_rx_pll_locked_3(rx_pll_locked[3]),
        .up_rx_rate_0(0),
        .up_rx_rate_1(0),
        .up_rx_rate_2(0),
        .up_rx_rate_3(0),
        .up_rx_rdata_0(),
        .up_rx_rdata_1(),
        .up_rx_rdata_2(),
        .up_rx_rdata_3(),
        .up_rx_ready_0(),
        .up_rx_ready_1(),
        .up_rx_ready_2(),
        .up_rx_ready_3(),
        .up_rx_rst_0(0),
        .up_rx_rst_1(0),
        .up_rx_rst_2(0),
        .up_rx_rst_3(0),
        .up_rx_rst_done_0(),
        .up_rx_rst_done_1(),
        .up_rx_rst_done_2(),
        .up_rx_rst_done_3(),
        .up_rx_sys_clk_sel_0(0),
        .up_rx_sys_clk_sel_1(0),
        .up_rx_sys_clk_sel_2(0),
        .up_rx_sys_clk_sel_3(0),
        .up_rx_user_ready_0(1),
        .up_rx_user_ready_1(1),
        .up_rx_user_ready_2(1),
        .up_rx_user_ready_3(1),
        .up_rx_wdata_0(0),
        .up_rx_wdata_1(0),
        .up_rx_wdata_2(0),
        .up_rx_wdata_3(0),
        .up_rx_wr_0(0),
        .up_rx_wr_1(0),
        .up_rx_wr_2(0),
        .up_rx_wr_3(0),
        .up_tx_addr_0(0),
        .up_tx_addr_1(0),
        .up_tx_addr_2(0),
        .up_tx_addr_3(0),
        .up_tx_diffctrl_0(0),
        .up_tx_diffctrl_1(0),
        .up_tx_diffctrl_2(0),
        .up_tx_diffctrl_3(0),
        .up_tx_enb_0(0),
        .up_tx_enb_1(0),
        .up_tx_enb_2(0),
        .up_tx_enb_3(0),
        .up_tx_lpm_dfe_n_0(0),
        .up_tx_lpm_dfe_n_1(0),
        .up_tx_lpm_dfe_n_2(0),
        .up_tx_lpm_dfe_n_3(0),
        .up_tx_out_clk_sel_0(0),
        .up_tx_out_clk_sel_1(0),
        .up_tx_out_clk_sel_2(0),
        .up_tx_out_clk_sel_3(0),
        .up_tx_pll_locked_0(tx_pll_locked[0]),
        .up_tx_pll_locked_1(tx_pll_locked[1]),
        .up_tx_pll_locked_2(tx_pll_locked[2]),
        .up_tx_pll_locked_3(tx_pll_locked[3]),
        .up_tx_postcursor_0(0),
        .up_tx_postcursor_1(0),
        .up_tx_postcursor_2(0),
        .up_tx_postcursor_3(0),
        .up_tx_precursor_0(0),
        .up_tx_precursor_1(0),
        .up_tx_precursor_2(0),
        .up_tx_precursor_3(0),
        .up_tx_rate_0(0),
        .up_tx_rate_1(0),
        .up_tx_rate_2(0),
        .up_tx_rate_3(0),
        .up_tx_rdata_0(),
        .up_tx_rdata_1(),
        .up_tx_rdata_2(),
        .up_tx_rdata_3(),
        .up_tx_ready_0(),
        .up_tx_ready_1(),
        .up_tx_ready_2(),
        .up_tx_ready_3(),
        .up_tx_rst_0(0),
        .up_tx_rst_1(0),
        .up_tx_rst_2(0),
        .up_tx_rst_3(0),
        .up_tx_rst_done_0(),
        .up_tx_rst_done_1(),
        .up_tx_rst_done_2(),
        .up_tx_rst_done_3(),
        .up_tx_sys_clk_sel_0(0),
        .up_tx_sys_clk_sel_1(0),
        .up_tx_sys_clk_sel_2(0),
        .up_tx_sys_clk_sel_3(0),
        .up_tx_user_ready_0(1),
        .up_tx_user_ready_1(1),
        .up_tx_user_ready_2(1),
        .up_tx_user_ready_3(1),
        .up_tx_wdata_0(0),
        .up_tx_wdata_1(0),
        .up_tx_wdata_2(0),
        .up_tx_wdata_3(0),
        .up_tx_wr_0(0),
        .up_tx_wr_1(0),
        .up_tx_wr_2(0),
        .up_tx_wr_3(0));

endmodule
